### ISSUE TITLE
HandleFunc and Group Commands

### ISSUE THREAD

**Issue by jjcazau** [yanzay/tbot#2]
Hi, currently my bot works in private chat but breaks in group chats. 

Telegram sends the /command in private chat but in group chat it sends /command@botname.
Currently the best solution i have is create 2 HandleFunc, one for each name. Eg:

bot.HandleFunc("/command", doFunction, "Descr")
bot.HandleFunc("/command@Botname", doFunction, "Descr")

Does tbot currently support a better method? like wildcards in command name, or automatically ignoring @groupname after commands.

**Comment by yanzay** [comment]
Hi @jjcazau, thanks for your report.

As a temporary workaround, you can define your commands like "/command{}" and it will catch all messages started with "/command".

But I plan to fix this issue, good catch. Thanks again.
