### ISSUE TITLE
How to use InlineKeyboard

### ISSUE THREAD

**Issue by rezam90** [yanzay/tbot#28]
Hi, I'm trying to have send a message with buttons bellow it.
there wasn't any example about this.
I don't know how to implement this with callback buttons.
can you help?

**Comment by eeonevision** [comment]
A good question )
There miss in docs, will fix it in future.
This code example helps you:
```go
buttons := []map[string]string{
	map[string]string{
		app.OrderCheckRequestsInlineBtn: fmt.Sprintf("check_order_%v", or.ID),
		app.OrderCancelInlineBtn:        fmt.Sprintf("cancel_order_%v", or.ID),
	},
}
message.ReplyInlineKeyboard(msg, buttons, tbot.WithDataInlineButtons)
```

**Comment by mrbesen** [comment]
The new inline example helped me.
