### ISSUE TITLE
Is possible using command with optional payload?

### ISSUE THREAD

**Issue by h4ckm03d** [yanzay/tbot#29]
Example:

command `/weather 10-10-2018` with `/weather` will get today. 
Is there any implementation using handlefunc with this scenario?

**Comment by eeonevision** [comment]
Yes, read docs more closely.
```go
bot.HandleFunc("/say {text}", SayHandler)
```

**Comment by h4ckm03d** [comment]
`bot.HandleFunc("/say {text}", SayHandler)`

I know using this can get variable `text`. but if command only `/say`, this not handled by SayHandler but default handler.
