### ISSUE TITLE
How to handle deep linking?callback query

### ISSUE THREAD

**Issue by baskara8** [yanzay/tbot#30]
For Example 
Q: /signin

A: Enter your login

Q: Somelogin

A: Enter you password

Q: Somepassword

A: Authorization success!

**Comment by eeonevision** [comment]
Maybe better will obtain variables from a command and parse it.
The handler can accept variables, like this:
```go
bot.HandleFunc("/say {text}", SayHandler)
```
If you want to use more standard way of interaction with a user. You can implement above logic with if...else construction.

Hope this tips helps you)
