### ISSUE TITLE
use semantic version for tags

### ISSUE THREAD

**Issue by pkgogo** [yanzay/tbot#33]
like v0.4.0, so it can work with go mod, thanks~

currently only v0.3.1 is recognized by go mod.

https://github.com/golang/go/issues/27528

**Comment by yanzay** [comment]
Done, you can check now tag v1.0

**Comment by vporoshok** [comment]
Hi! Seems like go mod ignore shrinked semantic version. Documentation notes that version should be in form v{major}.{minor}.{patch} https://github.com/golang/go/wiki/Modules#modules So `go mod` doesn't find tag `v1.0`. Could you please add tag with patch number?

**Comment by yanzay** [comment]
Added v1.0.0, please check if it works for you.

**Comment by vporoshok** [comment]
Yeah! It works. Thank you!

**Comment by yanzay** [comment]
Nice! Closing.
