### ISSUE TITLE
Can't make examples work

### ISSUE THREAD

**Issue by gudata** [yanzay/tbot#41]
All the examples give the same error

```
# command-line-arguments
commands/main.go:11:13: undefined: tbot.UpdateHandler
commands/main.go:12:17: undefined: tbot.Update
commands/main.go:20:9: undefined: tbot.New
commands/main.go:24:18: m.Chat undefined (type *tbot.Message has no field or method Chat)

```
and here is the code
```
package main

import (
	"log"
	"os"
	"time"

	"github.com/yanzay/tbot"
)

func stat(h tbot.UpdateHandler) tbot.UpdateHandler {
	return func(u *tbot.Update) {
		start := time.Now()
		h(u)
		log.Printf("Handle time: %v", time.Now().Sub(start))
	}
}

func main() {
	bot := tbot.New(os.Getenv("TELEGRAM_TOKEN"))
	c := bot.Client()
	bot.Use(stat) // add stat middleware to bot
	bot.HandleMessage("", func(m *tbot.Message) {
		c.SendMessage(m.Chat.ID, "hello!")
	})
	err := bot.Start()
	if err != nil {
		log.Fatal(err)
	}
}
````
The same is with the example from the Readme.md

**Comment by yanzay** [comment]
Looks like you're using v1 and running examples from v2, please make sure you set
```
require github.com/yanzay/tbot v2.0.0
```
in your `go.mod` file.

**Comment by yanzay** [comment]
Also, I've just updated version in examples and in go.mod itself so now it should work without any manual work.

**Comment by gudata** [comment]
Thanks!

**Comment by miketsukuba** [comment]
I tried to use the send message with golang 1.16, but receiving
.go:8:2: no required module provides package github.com/yanzay/tbot/v2: go.mod file not found in current directory or any parent directory; see 'go help modules'

(previously I had not problem with golang 1.13

Cheers
