### ISSUE TITLE
Cannot install and use the library

### ISSUE THREAD

**Issue by Invy55** [yanzay/tbot#49]
Hi everyone, I'm trying to install the library:
`go get github.com/yanzay/tbot/v2`
but it gaves me the following error:
```
package github.com/yanzay/tbot/v2: cannot find package "github.com/yanzay/tbot/v2" in any of:
        /usr/local/go/src/github.com/yanzay/tbot/v2 (from $GOROOT)
        /root/work/src/github.com/yanzay/tbot/v2 (from $GOPATH)
```
I'm on a Debian 9 machine and other libraries works perfect.
What can I do to solve this error?

**Comment by yanzay** [comment]
Which version of go do you use?
