### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by tierline1** [yanzay/tbot#50]
Can you provide an example of how to handle upload file/picture from user?
in the previous version there was a function HandleFile(), in this it is not

**Comment by scooby143** [comment]
yes, If you provide any example means it very usefull to all

**Comment by scooby143** [comment]
> Can you provide an example of how to handle upload file/picture from user?
> in the previous version there was a function HandleFile(), in this it is not

https://github.com/yanzay/tbot/blob/master/examples/getfile/main.go
