### ISSUE TITLE
Replyf function as in obsolete tbot

### ISSUE THREAD

**Issue by lhlhx** [yanzay/tbot#66]
I noticed it is quite hard to make replies when user triggered any handleMessage requests.

Is there a Replyf function as in obsolete golang tbot library for making stateful go tbots?

thank you! 

https://tutorials.botsfloor.com/develop-your-own-telegram-bot-with-golang-and-tbot-de726883b83c

**Comment by yanzay** [comment]
There is no more `Replyf` function, but you can get same result by using plain `SendMessage()` with `fmt.Sprintf()` like so:
```go
func replyHandler(m *tbot.Message) {
	c.SendMessage(m.Chat.ID, fmt.Sprintf("formatted %s", "text"))
}
```

**Comment by lhlhx** [comment]
Thank you for your explanation!

One more thing to ask, is there any function equivalent to register_next_step handler in PyTelegramBotAPI?

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py

If not, I am thinking of using HandleFunc with regexp "." for handling step states, is that a good idea?

Thanks!

**Comment by yanzay** [comment]
There is no equivalent to `register_next_step` in `tbot` so you need to implement it by hand using the persistence layer of your choice: file or some database.

I've done something similar in my small game, feel free to use it as an example (a bunch of old code, but still) https://github.com/yanzay/picasso/blob/master/login.go

**Comment by lhlhx** [comment]
Nice! I will try that out later.
Hopefully it works out and I will share the code.

Big thank you!
